Revert "Typedef "nc_type" if not defined. Should make netcdf on Ubuntu (3) works." Does not work... Still have error: src/Classes_NetCDF.hpp:37: error: invalid conversion from ‘int’ to ‘nc_type’
This reverts commit 781e6690ce17213dc5e044a8a630f2fea4654ab7.